#!/usr/bin/env python3

from rqt_gui.main import Main
from rqt_motion_system.motion_system_controller import MotionSystemController

import sys


plugin = 'rqt_motion_system.motion_system_controller.MotionSystemController'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))